from mercurial import commands, extensions
# Simple extension to provide a hook for manual commits only

"""commit hooks for manual commits

Mercurial provides no way for a commit hook to differentiate between
user-initiated commits and those generated by extensions like shelve,
graft, histedit or rebase.

This extension temporarily enables commit hooks for manual commits only
by temporary changing hooks.manualpre(txn)commit to hooks.pre(txn)commit.manual

In order to use it, add the following lines to your ``.hg/hgrc`` or
``~/.hgrc`` file::

    [extensions]
    manualcommithook=/path/to/this/extension
    [hooks]
    manualprecommit=/path/to/commit/hook
"""

def commit_with_hook(original_cmd, ui, repo, *pats, **opts):
    for hook_name in ("manualpretxncommit", "manualprecommit"):
        hook = ui.config("hooks", hook_name)
        if hook:
            temporary_hook_name = hook_name.replace("manual", "") + ".manual"
            if ui.config("hooks", temporary_hook_name):
                ui.warn("overriding existing {} hook\n".format(temporary_hook_name))

            ui.setconfig("hooks", temporary_hook_name, hook)

        return original_cmd(ui, repo, *pats, **opts)

def uisetup(ui):
    extensions.wrapcommand(commands.table, "commit", commit_with_hook)
